//! I/O ports
use tock_registers::register_bitfields;

register_bitfields![u8,
    pub Direction [
        B0 OFFSET(0) NUMBITS(1) [ Input = 0, Output = 1 ],
        B1 OFFSET(1) NUMBITS(1) [ Input = 0, Output = 1 ],
        B2 OFFSET(2) NUMBITS(1) [ Input = 0, Output = 1 ],
        B3 OFFSET(3) NUMBITS(1) [ Input = 0, Output = 1 ],
        B4 OFFSET(4) NUMBITS(1) [ Input = 0, Output = 1 ],
        B5 OFFSET(5) NUMBITS(1) [ Input = 0, Output = 1 ],
        B6 OFFSET(6) NUMBITS(1) [ Input = 0, Output = 1 ],
        B7 OFFSET(7) NUMBITS(1) [ Input = 0, Output = 1 ],
    ],
    pub Data [
        B0 OFFSET(0) NUMBITS(1) [],
        B1 OFFSET(1) NUMBITS(1) [],
        B2 OFFSET(2) NUMBITS(1) [],
        B3 OFFSET(3) NUMBITS(1) [],
        B4 OFFSET(4) NUMBITS(1) [],
        B5 OFFSET(5) NUMBITS(1) [],
        B6 OFFSET(6) NUMBITS(1) [],
        B7 OFFSET(7) NUMBITS(1) [],
    ],
    pub InputBufferControl [
        B0 OFFSET(0) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B1 OFFSET(1) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B2 OFFSET(2) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B3 OFFSET(3) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B4 OFFSET(4) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B5 OFFSET(5) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B6 OFFSET(6) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B7 OFFSET(7) NUMBITS(1) [ Disable = 0, Enable = 1 ],
    ],
    pub NmosOpenDrainControl [
        B0 OFFSET(0) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B1 OFFSET(1) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B2 OFFSET(2) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B3 OFFSET(3) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B4 OFFSET(4) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B5 OFFSET(5) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B6 OFFSET(6) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B7 OFFSET(7) NUMBITS(1) [ Disable = 0, Enable = 1 ],
    ],
    pub OpenDrainControl [
        B0 OFFSET(0) NUMBITS(2) [
            Cmos = 0b00,
            NmosOpenDrain = 0b01,
            PmosOpenDrain = 0b10,
        ],
        B1 OFFSET(2) NUMBITS(2) [
            Cmos = 0b00,
            NmosOpenDrain = 0b01,
            PmosOpenDrain = 0b10,
        ],
        B2 OFFSET(4) NUMBITS(2) [
            Cmos = 0b00,
            NmosOpenDrain = 0b01,
            PmosOpenDrain = 0b10,
        ],
        B3 OFFSET(6) NUMBITS(2) [
            Cmos = 0b00,
            NmosOpenDrain = 0b01,
            PmosOpenDrain = 0b10,
        ],
    ],
    pub PullUpControl [
        B0 OFFSET(0) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B1 OFFSET(1) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B2 OFFSET(2) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B3 OFFSET(3) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B4 OFFSET(4) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B5 OFFSET(5) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B6 OFFSET(6) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B7 OFFSET(7) NUMBITS(1) [ Disable = 0, Enable = 1 ],
    ],
    pub DriveCapacityControl [
        B0 OFFSET(0) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B1 OFFSET(1) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B2 OFFSET(2) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B3 OFFSET(3) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B4 OFFSET(4) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B5 OFFSET(5) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B6 OFFSET(6) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B7 OFFSET(7) NUMBITS(1) [ Disable = 0, Enable = 1 ],
    ],
    pub RouteToPeripheral [
        B0 OFFSET(0) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B1 OFFSET(1) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B2 OFFSET(2) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B3 OFFSET(3) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B4 OFFSET(4) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B5 OFFSET(5) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B6 OFFSET(6) NUMBITS(1) [ Disable = 0, Enable = 1 ],
        B7 OFFSET(7) NUMBITS(1) [ Disable = 0, Enable = 1 ],
    ],
];
