[package]
name = "r3_example_basic_qemu_rx"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
r3_port_rx = { path = "../../src/r3_port_rx" }
r3_kernel = { version = "0.1", features = ["system_time"] }
r3 = { version = "0.2" }
